[pytest]
markers =
    parquet_data: mark test as parquet data test
    smoke: mark test as smoke test
    facility_name_min_time_spent_per_visit_date: test for facility_name_min_time_spent_per_visit_date
    facility_type_avg_time_spent_per_visit_date: test for facility_type_avg_time_spent_per_visit_date
    patient_sum_treatment_cost_per_facility_type: test for patient_sum_treatment_cost_per_facility_type
    example: mark test as example
