[pytest]
# marks
markers =
    validate_csv: mark test as a CSV validation test
    unmarked: mark tests that have no explicit pytest marks

# python_files
python_files = test_*.py

# addopts
addopts = -v --tb=short --html=report.html --self-contained-html