[pytest]
# marks
markers =
    validate_csv: mark test as a CSV validation test
    unmarked: mark tests that have no explicit pytest marks

# python_files
python_files = test_*.py

# addopts
addopts = -v --tb=short --html=report.html --self-contained-html

rp_endpoint = https://reportportal.epam.com
rp_api_key = dqa-key_Vx3S8ZwkRy-yPHHScHAC6sjGnmBaVUwZmfIGMd9SkURHhcVoPeBcWGsuegZbYipF
rp_launch = My_First_Launch
rp_project = yevgenia_petrosyan_personal
rp_enable = True
rp_log_batch_size = 20